disabled_rules: # rule identifiers to exclude from running
  - file_length # https://github.com/realm/SwiftLint/blob/master/Rules.md#file-line-length
  - line_length # https://github.com/realm/SwiftLint/blob/master/Rules.md#line-length
  - force_cast # https://github.com/realm/SwiftLint/blob/master/Rules.md#force-cast
excluded: # paths to ignore during linting. Takes precedence over `included`.  
  - Pods
  - fusion/Common/stacktrace
included:
  - fusion
